// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: examples/protobuf/discount.proto

package discountpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscountFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Discount      int32                  `protobuf:"varint,2,opt,name=discount,proto3" json:"discount,omitempty"`
	CustomerType  string                 `protobuf:"bytes,3,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscountFact) Reset() {
	*x = DiscountFact{}
	mi := &file_examples_protobuf_discount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscountFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscountFact) ProtoMessage() {}

func (x *DiscountFact) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protobuf_discount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscountFact.ProtoReflect.Descriptor instead.
func (*DiscountFact) Descriptor() ([]byte, []int) {
	return file_examples_protobuf_discount_proto_rawDescGZIP(), []int{0}
}

func (x *DiscountFact) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DiscountFact) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *DiscountFact) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

func (x *DiscountFact) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type OrderFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items         []*Item                `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Discount      *DiscountFact          `protobuf:"bytes,5,opt,name=discount,proto3" json:"discount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFact) Reset() {
	*x = OrderFact{}
	mi := &file_examples_protobuf_discount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFact) ProtoMessage() {}

func (x *OrderFact) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protobuf_discount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFact.ProtoReflect.Descriptor instead.
func (*OrderFact) Descriptor() ([]byte, []int) {
	return file_examples_protobuf_discount_proto_rawDescGZIP(), []int{1}
}

func (x *OrderFact) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderFact) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderFact) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderFact) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderFact) GetDiscount() *DiscountFact {
	if x != nil {
		return x.Discount
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_examples_protobuf_discount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protobuf_discount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_examples_protobuf_discount_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_examples_protobuf_discount_proto protoreflect.FileDescriptor

const file_examples_protobuf_discount_proto_rawDesc = "" +
	"\n" +
	" examples/protobuf/discount.proto\x12\bdiscount\"{\n" +
	"\fDiscountFact\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\x12\x1a\n" +
	"\bdiscount\x18\x02 \x01(\x05R\bdiscount\x12#\n" +
	"\rcustomer_type\x18\x03 \x01(\tR\fcustomerType\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\xc4\x01\n" +
	"\tOrderFact\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x01R\vtotalAmount\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12$\n" +
	"\x05items\x18\x04 \x03(\v2\x0e.discount.ItemR\x05items\x122\n" +
	"\bdiscount\x18\x05 \x01(\v2\x16.discount.DiscountFactR\bdiscount\"\x87\x01\n" +
	"\x04Item\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategoryB<Z:github.com/hungpdn/grule-plus/examples/protobuf/discountpbb\x06proto3"

var (
	file_examples_protobuf_discount_proto_rawDescOnce sync.Once
	file_examples_protobuf_discount_proto_rawDescData []byte
)

func file_examples_protobuf_discount_proto_rawDescGZIP() []byte {
	file_examples_protobuf_discount_proto_rawDescOnce.Do(func() {
		file_examples_protobuf_discount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protobuf_discount_proto_rawDesc), len(file_examples_protobuf_discount_proto_rawDesc)))
	})
	return file_examples_protobuf_discount_proto_rawDescData
}

var file_examples_protobuf_discount_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_protobuf_discount_proto_goTypes = []any{
	(*DiscountFact)(nil), // 0: discount.DiscountFact
	(*OrderFact)(nil),    // 1: discount.OrderFact
	(*Item)(nil),         // 2: discount.Item
}
var file_examples_protobuf_discount_proto_depIdxs = []int32{
	2, // 0: discount.OrderFact.items:type_name -> discount.Item
	0, // 1: discount.OrderFact.discount:type_name -> discount.DiscountFact
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_examples_protobuf_discount_proto_init() }
func file_examples_protobuf_discount_proto_init() {
	if File_examples_protobuf_discount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protobuf_discount_proto_rawDesc), len(file_examples_protobuf_discount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protobuf_discount_proto_goTypes,
		DependencyIndexes: file_examples_protobuf_discount_proto_depIdxs,
		MessageInfos:      file_examples_protobuf_discount_proto_msgTypes,
	}.Build()
	File_examples_protobuf_discount_proto = out.File
	file_examples_protobuf_discount_proto_goTypes = nil
	file_examples_protobuf_discount_proto_depIdxs = nil
}
